export const GET_ALL_PULL_REQUEST = 'GET_ALL_PULL_REQUEST';
export const GET_ALL_PULL_SUCCESS = 'GET_ALL_PULL_SUCCESS';
export const GET_ALL_PULL_FAILURE = 'GET_ALL_PULL_FAILURE';

export const GET_ALL_ISSUES_REQUEST = 'GET_ALL_ISSUES_REQUEST';
export const GET_ALL_ISSUES_SUCCESS = 'GET_ALL_ISSUES_SUCCESS';
export const GET_ALL_ISSUES_FAILURE = 'GET_ALL_ISSUES_FAILURE';